import type { Metadata } from "next";
import { Barlow, Public_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${publicSans.variable} font-sans antialiased min-h-screen flex flex-col text-body`}
      >
        <Header/>
        {/* Card shall be visible at centre of whole page */}
        <div className="fixed inset-0 flex justify-center items-center">
          <main className="w-full max-w-full flex flex-col justify-center">{children}</main>
        </div>
      </body>
    </html>
  );
}
